//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public string Id { get; set; }
        public string FIO { get; set; }
        public string Spec { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string Password { get; set; }
    }
}
